services:
  db:
    image: postgres:17-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/storage/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:8.0-M02-alpine
    restart: always
    volumes:
      - ./docker/storage/redis-data:/root/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "6379:6379"